export const GET_COTEGORIES = "GET_COTEGORIES"
export const LOADING_COTEGORIES = "LOADING_COTEGORIES"
export const ERROR_COTEGORIES = "ERROR_COTEGORIES"  

export const GET_CATEGORIES_DETAIL = "GET_CATEGORIES_DETAIL"
export const LOADING_CATEGORIES_DETAIL = "LOADING_CATEGORIES_DETAIL"
export const ERROR_CATEGORIES_DETAIL = "ERROR_CATEGORIES_DETAIL"  