export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES"
export const LOADING_SUB_CATEGORIES = "LOADING_SUB_CATEGORIES"
export const ERROR_SUB_CATEGORIES = "ERROR_SUB_CATEGORIES"
export const GET_SUB_CATEGORIES_DETAIL = "GET_SUB_CATEGORIES_DETAIL"